 export enum ACTIONS_CODE {
    work_list_show = "work_list_show",
    work_list_update = "work_list_update",
    work_item_show = "work_item_show",
    work_item_update = "work_item_update",
    work_item_info_show = "work_item_info_show",
    work_item_history_show = "work_item_history_show",
    agent_channels_show = 'agent_channels_show',
    agent_channels_control = 'agent_channels_control',
    agent_channels_update = 'agent_channels_update',
    agent_commands_show= 'agent_commands_show',
    agent_commands_update= 'agent_commands_update',
    agent_state_show = 'agent_state_show',
    agent_state_update = 'agent_state_update',
    agent_actionbar_show = 'agent_actionbar_show',
    login_show = 'login_show',
    login_hide = 'login_hide',
    phonebar_show = 'phonebar_show',
    phonebar_hide = 'phonebar_hide',
    voice_media_interaction_show = 'voice_media_interaction_show',
    voice_media_interaction_update = 'voice_media_interaction_update',
}

 export enum ACTIONS_REST_KEY  {
    // workitem list
    work_list_show = "work_list_show",
    work_list_update = "work_list_update",
    work_item_update = "work_item_update",
    work_list_no_timer_update = "work_list_no_timer_update",
    work_list_hide_update = "work_list_hide_update",
    work_item_accepted = "work_item_accepted",
    // work item
    work_item_show = "work_item_show",
    work_item_1_current_false_update = "work_item_1_current_false_update",
    work_item_1_current_true_update = "work_item_1_current_true_update",
    work_item_1_opened_false_update = "work_item_1_opened_false_update",
    work_item_1_opened_true_update = "work_item_1_opened_true_update",
    work_item_1_disconnected_false_update = "work_item_1_disconnected_false_update",
    work_item_1_disconnected_true_update = "work_item_1_disconnected_true_update",
    work_item_1_transferred_true_update = "work_item_1_transferred_true_update",
    work_item_1_transferred_false_update = "work_item_1_transferred_false_update",
    work_item_2_current_false_update = "work_item_2_current_false_update",
    work_item_2_current_true_update = "work_item_2_current_true_update",
    work_item_2_opened_false_update = "work_item_2_opened_false_update",
    work_item_2_opened_true_update = "work_item_2_opened_true_update",
    work_item_2_disconnected_false_update = "work_item_2_disconnected_false_update",
    work_item_2_disconnected_true_update = "work_item_2_disconnected_true_update",
    work_item_2_transferred_true_update = "work_item_2_transferred_true_update",
    work_item_2_transferred_false_update = "work_item_2_transferred_false_update",
    work_item_info_show = "work_item_info_show",
    work_item_history_show = "work_item_history_show",
    // agent channel
    agent_channels_show = 'agent_channels_show',
    agent_channels_control = 'agent_channels_control',
    agent_channels_update = 'agent_channels_update',
    agent_channels_zero_update = 'agent_channels_zero_update',
    agent_channels_one_update = 'agent_channels_one_update',
    agent_channels_two_update = 'agent_channels_two_update',
    agent_channels_three_update = 'agent_channels_three_update',
    agent_channels_four_update = 'agent_channels_four_update',
    agent_channels_2_enabled_2_disabled_update = 'agent_channels_2_enabled_2_disabled_update',
    // agent command
    agent_commands_all_enabled_show= 'agent_commands_all_enabled_show',
    agent_commands_all_disabled_show = 'agent_commands_all_disabled_show',
    agent_commands_all_enabled_update = 'agent_commands_all_enabled_update',
    agent_commands_all_disabled_update = 'agent_commands_all_disabled_update',
    // agent state
    agent_state_show = 'agent_state_show',
    agent_state_update = 'agent_state_update',
    agent_state_LOGGED_OUT_update = 'agent_state_LOGGED_OUT_update',
    agent_state_time_1_update = 'agent_state_time_1_update',
    agent_state_time_2_update = 'agent_state_time_2_update',
    agent_state_time_300_update = 'agent_state_time_300_update',
    agent_state_time_3000_update = 'agent_state_time_3000_update',
    agent_state_time_30000_update = 'agent_state_time_30000_update',
    // login
    login_show = 'login_show',
    login_hide = 'login_hide',
    // phonebar
    phonebar_show = 'phonebar_show',
    phonebar_hide = 'phonebar_hide',
    voice_media_interaction_show = 'voice_media_interaction_show',
    voice_media_interaction_update = 'voice_media_interaction_update',
}

export const ACTIONS_KEY_MAP: {[key in ACTIONS_REST_KEY]: ACTIONS_CODE} = {
    // work list
    [ACTIONS_REST_KEY.work_list_show]: ACTIONS_CODE.work_list_show,
    [ACTIONS_REST_KEY.work_list_update]: ACTIONS_CODE.work_list_update,
    [ACTIONS_REST_KEY.work_item_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_list_hide_update]: ACTIONS_CODE.work_list_update,
    [ACTIONS_REST_KEY.work_item_accepted]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_list_no_timer_update]: ACTIONS_CODE.work_list_update,
    // work item
    [ACTIONS_REST_KEY.work_item_show]: ACTIONS_CODE.work_item_show,
    [ACTIONS_REST_KEY.work_item_1_current_false_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_1_current_true_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_1_opened_false_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_1_opened_true_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_1_disconnected_false_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_1_disconnected_true_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_1_transferred_true_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_1_transferred_false_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_info_show]: ACTIONS_CODE.work_item_info_show,
    [ACTIONS_REST_KEY.work_item_history_show]: ACTIONS_CODE.work_item_history_show,

    [ACTIONS_REST_KEY.work_item_2_current_false_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_2_current_true_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_2_opened_false_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_2_opened_true_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_2_disconnected_false_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_2_disconnected_true_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_2_transferred_true_update]: ACTIONS_CODE.work_item_update,
    [ACTIONS_REST_KEY.work_item_2_transferred_false_update]: ACTIONS_CODE.work_item_update,
    // agent channel
    [ACTIONS_REST_KEY.agent_channels_show]: ACTIONS_CODE.agent_channels_show,
    [ACTIONS_REST_KEY.agent_channels_control]: ACTIONS_CODE.agent_channels_control,
    [ACTIONS_REST_KEY.agent_channels_update]: ACTIONS_CODE.agent_channels_update,
    [ACTIONS_REST_KEY.agent_channels_zero_update]: ACTIONS_CODE.agent_channels_update,
    [ACTIONS_REST_KEY.agent_channels_one_update]: ACTIONS_CODE.agent_channels_update,
    [ACTIONS_REST_KEY.agent_channels_two_update]: ACTIONS_CODE.agent_channels_update,
    [ACTIONS_REST_KEY.agent_channels_three_update]: ACTIONS_CODE.agent_channels_update,
    [ACTIONS_REST_KEY.agent_channels_four_update]: ACTIONS_CODE.agent_channels_update,
    [ACTIONS_REST_KEY.agent_channels_2_enabled_2_disabled_update]: ACTIONS_CODE.agent_channels_update,
    // agent command
    [ACTIONS_REST_KEY.agent_commands_all_disabled_show]: ACTIONS_CODE.agent_commands_show,
    [ACTIONS_REST_KEY.agent_commands_all_enabled_show]: ACTIONS_CODE.agent_commands_show,
    [ACTIONS_REST_KEY.agent_commands_all_disabled_update]: ACTIONS_CODE.agent_commands_update,
    [ACTIONS_REST_KEY.agent_commands_all_enabled_update]: ACTIONS_CODE.agent_commands_update,
    // agent state
    [ACTIONS_REST_KEY.agent_state_show]: ACTIONS_CODE.agent_state_show,
    [ACTIONS_REST_KEY.agent_state_update]: ACTIONS_CODE.agent_state_update,
    [ACTIONS_REST_KEY.agent_state_time_1_update]: ACTIONS_CODE.agent_state_update,
    [ACTIONS_REST_KEY.agent_state_time_2_update]: ACTIONS_CODE.agent_state_update,
    [ACTIONS_REST_KEY.agent_state_time_300_update]: ACTIONS_CODE.agent_state_update,
    [ACTIONS_REST_KEY.agent_state_time_3000_update]: ACTIONS_CODE.agent_state_update,
    [ACTIONS_REST_KEY.agent_state_time_30000_update]: ACTIONS_CODE.agent_state_update,
    [ACTIONS_REST_KEY.agent_state_LOGGED_OUT_update]: ACTIONS_CODE.agent_state_update,
    // login
    [ACTIONS_REST_KEY.login_show]: ACTIONS_CODE.login_show,
    [ACTIONS_REST_KEY.login_hide]: ACTIONS_CODE.login_hide,
    // phonebar
    [ACTIONS_REST_KEY.phonebar_show]: ACTIONS_CODE.phonebar_show,
    [ACTIONS_REST_KEY.phonebar_hide]: ACTIONS_CODE.phonebar_hide,
    // voice media interaction
    [ACTIONS_REST_KEY.voice_media_interaction_show]: ACTIONS_CODE.voice_media_interaction_show,
    [ACTIONS_REST_KEY.voice_media_interaction_update]: ACTIONS_CODE.voice_media_interaction_update,
}

